import type { SiteData, SolutionData, TrackData } from '~/server-utils/data';
// Statically imported build-time JSON — generated by the exercism-data module.
// No runtime filesystem access; this gets bundled into the SSR + client output.
// @ts-expect-error generated file
import generated from '~/app/data.generated.json';

const data: SiteData = generated as SiteData;

export function useSiteData(): SiteData {
  return data;
}

export function useTracks(): TrackData[] {
  return data.tracks;
}

export function useSolutions(): SolutionData[] {
  return data.solutions;
}

export function useTrack(slug: string): TrackData | null {
  return data.tracks.find((t) => t.slug === slug) ?? null;
}

export function useSolution(trackSlug: string, exerciseSlug: string): SolutionData | null {
  return data.solutions.find((s) => s.trackSlug === trackSlug && s.slug === exerciseSlug) ?? null;
}

export function useStats() {
  return data.stats;
}